export const lang = {
    en: {
        home: "Home",
        askGptBtn: "Ask Gemini",
        signIn: "Sign in",
        signUp: "Sign up",
        signOut: "Sign out",
        playBtn: "Play",
        moreInfoBtn: "More info",
        gptInputPlaceholder: "Chat with Gemini",
        gptSendBtn: "Send",
        inputNamePlaceholder: "Enter Full Name",
        inputNameErrorMessage: "Enter Name",
        inputEmailPlaceholder: "Enter email address",
        inputEmailErrorMessage: "Invalid email",
        inputPasswordPlaceholder: "Enter password",
        inputPasswordErrorMessage: "Invalid password",
        or: "OR", 
        signInUsingCode: "Use a sign-in code",
        signUpUsingCode: "Sign-up using code",
        forgetPassword: "Forgot password?",
        newToFlixGpt: "New to FlixGPT? ",
        alreadyHaveAccount: "Already have an account? ",
        signUpNow: "Sign up now.",
        login: "Login",
    },
    hindi: {
        home: "होम",
        askGptBtn: "जीपीटी से पूछो",
        signIn: "दाखिल करना",
        signUp: "साइन अप करें",
        signOut: "साइन आउट",
        playBtn: "चलाएं",
        moreInfoBtn: "और जानकारी",
        gptInputPlaceholder: "जीपीटी के साथ चैट करें",
        gptSendBtn: "भेजना", 
        inputNamePlaceholder: "पूरा नाम दर्ज करें",
        inputNameErrorMessage: "Enter Name",
        inputEmailPlaceholder: "Enter email address",
        inputEmailErrorMessage: "Invalid email",
        inputPasswordPlaceholder: "Enter password",
        inputPasswordErrorMessage: "Invalid password",
        or: "OR", 
        signInUsingCode: "Use a sign-in code",
        signUpUsingCode: "Sign-up using code",
        forgetPassword: "Forgot password?",
        newToFlixGpt: "New to FlixGPT? ",
        alreadyHaveAccount: "Already have an account? ",
        signUpNow: "Sign up now.",
        login: "Login",
    },
    bengali: {
        home: "হোম",
        askGptBtn: "জিপিটি জিজ্ঞাসা করুন",
        signIn: "সাইন ইন করুন",
        signUp: "সাইন আপ করুন",
        signOut: "সাইন আউট",
        playBtn: "চালান",
        moreInfoBtn: "আরো তথ্য",
        gptInputPlaceholder: "জিপিটির সাথে চ্যাট করুন",
        gptSendBtn: "পাঠান",
        inputNamePlaceholder: "পুরো নাম লিখুন",
        inputNameErrorMessage: "Enter Name",
        inputEmailPlaceholder: "Enter email address",
        inputEmailErrorMessage: "Invalid email",
        inputPasswordPlaceholder: "Enter password",
        inputPasswordErrorMessage: "Invalid password",
        or: "OR", 
        signInUsingCode: "Use a sign-in code",
        signUpUsingCode: "Sign-up using code",
        forgetPassword: "Forgot password?",
        newToFlixGpt: "New to FlixGPT? ",
        alreadyHaveAccount: "Already have an account? ",
        signUpNow: "Sign up now.",
        login: "Login",
    },
    spanish: {
        home: "Hogar",
        askGptBtn: "Pregúntale a GPT",
        signIn: "Iniciar sesión",
        signUp: "Inscribirse",
        signOut: "desconectar",
        playBtn: "Jugar",
        moreInfoBtn: "Más información",
        gptInputPlaceholder: "Chatea con GPT",
        gptSendBtn: "Enviar",
        inputNamePlaceholder: "Ingrese el nombre completo",
        inputNameErrorMessage: "Enter Name",
        inputEmailPlaceholder: "Enter email address",
        inputEmailErrorMessage: "Invalid email",
        inputPasswordPlaceholder: "Enter password",
        inputPasswordErrorMessage: "Invalid password",
        or: "OR", 
        signInUsingCode: "Use a sign-in code",
        signUpUsingCode: "Sign-up using code",
        forgetPassword: "Forgot password?",
        newToFlixGpt: "New to FlixGPT? ",
        alreadyHaveAccount: "Already have an account? ",
        signUpNow: "Sign up now.",
        login: "Login",
    },
    tamil: {
        home: "வீடு",
        askGptBtn: "gpt கேளுங்கள்",
        signIn: "உள்நுழைக",
        signUp: "பதிவு செய்யவும்",
        signOut: "வெளியேறு",
        playBtn: "விளையாடு",
        moreInfoBtn: "மேலும் தகவல்",
        gptInputPlaceholder: "gpt உடன் அரட்டை அடிக்கவும்",
        gptSendBtn: "அனுப்பு",
        inputNamePlaceholder: "முழுப் பெயரை உள்ளிடவும்",
        inputNameErrorMessage: "Enter Name",
        inputEmailPlaceholder: "Enter email address",
        inputEmailErrorMessage: "Invalid email",
        inputPasswordPlaceholder: "Enter password",
        inputPasswordErrorMessage: "Invalid password",
        or: "OR", 
        signInUsingCode: "Use a sign-in code",
        signUpUsingCode: "Sign-up using code",
        forgetPassword: "Forgot password?",
        newToFlixGpt: "New to FlixGPT? ",
        alreadyHaveAccount: "Already have an account? ",
        signUpNow: "Sign up now.",
        login: "Login",
    },
    telugu: {
        home: "ఇల్లు",
        askGptBtn: "gpt ని అడగండి",
        signIn: "సైన్ ఇన్ చేయండి",
        signUp: "సైన్ అప్ చేయండి",
        signOut: "సైన్ అవుట్",
        playBtn: "ఆడండి",
        moreInfoBtn: "మరింత సమాచారం",
        gptInputPlaceholder: "gpt తో చాట్ చేయండి",
        gptSendBtn: "పంపండి",
        inputNamePlaceholder: "పూర్తి పేరును నమోదు చేయండి",
        inputNameErrorMessage: "Enter Name",
        inputEmailPlaceholder: "Enter email address",
        inputEmailErrorMessage: "Invalid email",
        inputPasswordPlaceholder: "Enter password",
        inputPasswordErrorMessage: "Invalid password",
        or: "OR", 
        signInUsingCode: "Use a sign-in code",
        signUpUsingCode: "Sign-up using code",
        forgetPassword: "Forgot password?",
        newToFlixGpt: "New to FlixGPT? ",
        alreadyHaveAccount: "Already have an account? ",
        signUpNow: "Sign up now.",
        login: "Login",
    }
}

export const languageList = [{identifier:"en", value:"English"}, {identifier:"bengali", value:"Bengali"}, {identifier:"hindi", value:"Hindi"}, {identifier:"spanish", value:"Spanish"}, {identifier:"tamil", value:"Tamil"}, {identifier:"telugu", value:"Telugu"}];