export const lang = {
    en: {
        home: "Home",
        askGptBtn: "FlixAI",
        signIn: "Sign in",
        signUp: "Sign up",
        signOut: "Sign out",
        playBtn: "Play",
        moreInfoBtn: "More info",
        gptInputPlaceholder: "Chat with FlixAI",
        gptSendBtn: "Send",
        inputNamePlaceholder: "Enter Full Name",
        inputNameErrorMessage: "Please Enter Name",
        inputEmailPlaceholder: "Enter email address",
        inputEmailErrorMessage: "Invalid email address",
        inputPasswordPlaceholder: "Enter your password",
        inputPasswordErrorMessage: "Invalid password, please try again",
        or: "OR", 
        signInUsingCode: "Use a sign-in code",
        signUpUsingCode: "Sign-up using code",
        forgetPassword: "Forgot password?",
        newToFlixGpt: "New to FlixGPT? ",
        alreadyHaveAccount: "Already have an account? ",
        signUpNow: "Sign up now.",
        login: "Login",
    },
    hindi: {
        home: "होम",
        askGptBtn: "FlixAI",
        signIn: "दाखिल करना",
        signUp: "साइन अप करें",
        signOut: "साइन आउट",
        playBtn: "चलाएं",
        moreInfoBtn: "और जानकारी",
        gptInputPlaceholder: "FlixAI के साथ चैट करें",
        gptSendBtn: "भेजना", 
        inputNamePlaceholder: "पूरा नाम दर्ज करें",
        inputNameErrorMessage: "कृपया अपना नाम दर्ज करें",
        inputEmailPlaceholder: "ईमेल पता दर्ज करें",
        inputEmailErrorMessage: "अमान्य ईमेल पता",
        inputPasswordPlaceholder: "अपना कूटशब्द भरें",
        inputPasswordErrorMessage: "अमान्य पासवर्ड, कृपया पुनः प्रयास करें",
        or: "या", 
        signInUsingCode: "साइन-इन कोड का उपयोग करें",
        signUpUsingCode: "कोड का उपयोग करके साइन-अप करें",
        forgetPassword: "पासवर्ड भूल गए?",
        newToFlixGpt: "फ़्लिक्सजीपीटी पर नए हैं? ",
        alreadyHaveAccount: "क्या आपके पास पहले से एक खाता मौजूद है? ",
        signUpNow: "अभी साइनअप करें।",
        login: "लॉग इन करें",
    },
    bengali: {
        home: "হোম",
        askGptBtn: "ফ্লিক্সএআই",
        signIn: "সাইন ইন করুন",
        signUp: "সাইন আপ করুন",
        signOut: "সাইন আউট",
        playBtn: "চালান",
        moreInfoBtn: "আরো তথ্য",
        gptInputPlaceholder: "ফ্লিক্সএআই এর সাথে চ্যাট করুন",
        gptSendBtn: "পাঠান",
        inputNamePlaceholder: "পুরো নাম লিখুন",
        inputNameErrorMessage: "দয়া করে আপনার নাম লিখুন",
        inputEmailPlaceholder: "ইমেল ঠিকানা লিখুন",
        inputEmailErrorMessage: "অবৈধ ইমেল",
        inputPasswordPlaceholder: "পাসওয়ার্ড লিখুন",
        inputPasswordErrorMessage: "অবৈধ পাসওয়ার্ড। আবার চেষ্টা করুন",
        or: "বা", 
        signInUsingCode: "একটি সাইন ইন কোড ব্যবহার করুন",
        signUpUsingCode: "কোড ব্যবহার করে সাইন আপ করুন",
        forgetPassword: "পাসওয়ার্ড ভুলে গেছেন?",
        newToFlixGpt: "FlixGPT এ নতুন? ",
        alreadyHaveAccount: "ইতিমধ্যে একটি অ্যাকাউন্ট আছে? ",
        signUpNow: "এখন সাইন আপ করুন.",
        login: "লগইন করুন",
    },

    // spanish: {
    //     home: "Hogar",
    //     askGptBtn: "Pregúntale a GPT",
    //     signIn: "Iniciar sesión",
    //     signUp: "Inscribirse",
    //     signOut: "desconectar",
    //     playBtn: "Jugar",
    //     moreInfoBtn: "Más información",
    //     gptInputPlaceholder: "Chatea con GPT",
    //     gptSendBtn: "Enviar",
    //     inputNamePlaceholder: "Ingrese el nombre completo",
    //     inputNameErrorMessage: "Enter Name",
    //     inputEmailPlaceholder: "Enter email address",
    //     inputEmailErrorMessage: "Invalid email",
    //     inputPasswordPlaceholder: "Enter password",
    //     inputPasswordErrorMessage: "Invalid password",
    //     or: "OR", 
    //     signInUsingCode: "Use a sign-in code",
    //     signUpUsingCode: "Sign-up using code",
    //     forgetPassword: "Forgot password?",
    //     newToFlixGpt: "New to FlixGPT? ",
    //     alreadyHaveAccount: "Already have an account? ",
    //     signUpNow: "Sign up now.",
    //     login: "Login",
    // },
    // tamil: {
    //     home: "வீடு",
    //     askGptBtn: "gpt கேளுங்கள்",
    //     signIn: "உள்நுழைக",
    //     signUp: "பதிவு செய்யவும்",
    //     signOut: "வெளியேறு",
    //     playBtn: "விளையாடு",
    //     moreInfoBtn: "மேலும் தகவல்",
    //     gptInputPlaceholder: "gpt உடன் அரட்டை அடிக்கவும்",
    //     gptSendBtn: "அனுப்பு",
    //     inputNamePlaceholder: "முழுப் பெயரை உள்ளிடவும்",
    //     inputNameErrorMessage: "Enter Name",
    //     inputEmailPlaceholder: "Enter email address",
    //     inputEmailErrorMessage: "Invalid email",
    //     inputPasswordPlaceholder: "Enter password",
    //     inputPasswordErrorMessage: "Invalid password",
    //     or: "OR", 
    //     signInUsingCode: "Use a sign-in code",
    //     signUpUsingCode: "Sign-up using code",
    //     forgetPassword: "Forgot password?",
    //     newToFlixGpt: "New to FlixGPT? ",
    //     alreadyHaveAccount: "Already have an account? ",
    //     signUpNow: "Sign up now.",
    //     login: "Login",
    // },
    // telugu: {
    //     home: "ఇల్లు",
    //     askGptBtn: "gpt ని అడగండి",
    //     signIn: "సైన్ ఇన్ చేయండి",
    //     signUp: "సైన్ అప్ చేయండి",
    //     signOut: "సైన్ అవుట్",
    //     playBtn: "ఆడండి",
    //     moreInfoBtn: "మరింత సమాచారం",
    //     gptInputPlaceholder: "gpt తో చాట్ చేయండి",
    //     gptSendBtn: "పంపండి",
    //     inputNamePlaceholder: "పూర్తి పేరును నమోదు చేయండి",
    //     inputNameErrorMessage: "Enter Name",
    //     inputEmailPlaceholder: "Enter email address",
    //     inputEmailErrorMessage: "Invalid email",
    //     inputPasswordPlaceholder: "Enter password",
    //     inputPasswordErrorMessage: "Invalid password",
    //     or: "OR", 
    //     signInUsingCode: "Use a sign-in code",
    //     signUpUsingCode: "Sign-up using code",
    //     forgetPassword: "Forgot password?",
    //     newToFlixGpt: "New to FlixGPT? ",
    //     alreadyHaveAccount: "Already have an account? ",
    //     signUpNow: "Sign up now.",
    //     login: "Login",
    // }
}

// export const languageList = [{identifier:"en", value:"English"}, {identifier:"bengali", value:"Bengali"}, {identifier:"hindi", value:"Hindi"}, {identifier:"spanish", value:"Spanish"}, {identifier:"tamil", value:"Tamil"}, {identifier:"telugu", value:"Telugu"}];

export const languageList = [{identifier:"en", value:"English"}, {identifier:"bengali", value:"Bengali"}, {identifier:"hindi", value:"Hindi"}];